 name: Play que promove para LCE
  hosts: localhost
  gather_facts: false
  become: false
  tasks:

    - name: Itera no arquivo de tasks para cada um dos Lifecycle Environments
      loop: "{{ survey_cvs }}"
      ansible.builtin.include_tasks: tasks_promove_cvs.yml

...
