---
- name: Play que realiza a atualização de SO das máquinas de desenvolvimento
  hosts: qa1.lab1.example.com
  become: true
  gather_facts: false
  tasks:

    - name: Atualiza o SO
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Verifica necessidade de restart, reiniciando a máquina se preciso
      block:
        - name: Verifica a necessidade de restart
          ansible.builtin.shell: needs-restarting --reboothint
      rescue:
        - name: Faz o reboot caso necessário
          ansible.builtin.reboot:
            reboot_timeout: 300
...
